log_level = "debug"
gc_udp_port = 14550
gc_reply_port = 9999
fc_destination = "db332f13541eb2e4b47d02923fbbcb9a"

[radio_config]
module = 0  # RadioA = 0, RadioB = 1
freq = 869535
channel = 11
channel_spacing = 200
tx_power = 10

[radio_config.phy_config]
type = "Ofdm"

[radio_config.phy_config.data]
mcs = 6
opt = 0
